name: 'Send Slack Webhook'

description: 'Wait a designated number of milliseconds'

inputs:
  slack-webhook-url:
    description: 'Slack webhook URL'
    required: true
  
outputs:
runs:
  using: 'node12'
  main: 'dist/index.js'
