name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - v1
      - 'releases/*'

jobs:
  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
