name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - v1
      - 'releases/*'

jobs:
  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        pull-request-sha: ${{github.event.pull_request.head.sha }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
        job-name: test
        job-status: ${{job.status}}